execute pathogen#infect()

set nocompatible
scriptencoding utf-8

syntax on
set t_Co=256
let g:solarized_termcolors=256
set background=dark
" color molokai
colorscheme solarized


"indenting
filetype on
filetype indent on
filetype plugin on
set nocindent
set autoindent
"set shiftwidth=4
"set tabstop=4
set smartindent
" 2 whitespace tab
" set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
" 4 whitespace tab
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

set wrap!

"delimitMate config
"imap <C-c> <CR><Esc>O

set mouse=a 				" mouse support
set number
set cul

"whitespace display
set pastetoggle=<f5>
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set list

"js indexting plugin configuration
set regexpengine=1


set showmatch 				" show matching brackets
"autocomplete
set incsearch				" find as you type search
set incsearch hlsearch		" highlight found items
set wildmenu				" show list instead of just completing

"fix for apps that monitor the fs (livereload etc)
set backupcopy=yes

"removes trailing whitespaces on save
autocmd BufWritePre * :%s/\s\+$//e

"ctrp config
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
" let g:ctrlp_custom_ignore = '\v[\/](node_modules|target|dist|ext|test|docs)|(\.(swp|ico|git|svn))$'
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif
"ALE
let g:ale_completion_enabled = 1
" let g:ale_linters = {
" \   'javascript': ['eslint'],
" \   'typescript': ['tsserver', 'tslint'],
" \}
"
let g:ale_virtualtext_cursor = 1

nmap <silent> <C-o> <Plug>(ale_detail)
let g:ale_change_sign_column_color = 1

" ag.vim
" ale
" ctrlp.vim
" tcomment_vim
" typescript-vim
" ultisnips
" vim-colors-solarized
" vim-javascript
" vim-snippets
" vim-surround
" vim-todo-lists
